FROM openjdk:17-jdk-slim-buster

RUN apt-get update && apt-get install -y curl tar bash procps git

ARG MAVEN_VERSION=3.9.0

ARG USER_HOME_DIR="/root"

ARG SHA=1ea149f4e48bc7b34d554aef86f948eca7df4e7874e30caf449f3708e4f8487c71a5e5c072a05f17c60406176ebeeaf56b5f895090c7346f8238e2da06cf6ecd

ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

# 5- Create the directories, download maven, validate the download, install it, remove downloaded file and set links
RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && echo "Downlaoding maven" \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  \
  && echo "Checking download hash" \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  \
  && echo "Unziping maven" \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  \
  && echo "Cleaning and setting links" \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# 6- Define environmental variables required by Maven, like Maven_Home directory and where the maven repo is located
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

WORKDIR /app

RUN git clone https://github.com/gnuvinicius/act-digital-challenge.git

WORKDIR /app/act-digital-challenge/votacao

ARG POSTGRES_DATABASE=assembleiadb-dev
ARG POSTGRES_USER=actdigitalbuser
ARG POSTGRES_PASSWD=

ARG QUEUE_PASSWD=

RUN mvn -DskipTests package

WORKDIR /app/act-digital-challenge/votacao/target

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "votacao-1.0.0.jar"]